module.exports = (function() {
var __MODS__ = {};
var __DEFINE__ = function(modId, func, req) { var m = { exports: {}, _tempexports: {} }; __MODS__[modId] = { status: 0, func: func, req: req, m: m }; };
var __REQUIRE__ = function(modId, source) { if(!__MODS__[modId]) return require(source); if(!__MODS__[modId].status) { var m = __MODS__[modId].m; m._exports = m._tempexports; var desp = Object.getOwnPropertyDescriptor(m, "exports"); if (desp && desp.configurable) Object.defineProperty(m, "exports", { set: function (val) { if(typeof val === "object" && val !== m._exports) { m._exports.__proto__ = val.__proto__; Object.keys(val).forEach(function (k) { m._exports[k] = val[k]; }); } m._tempexports = val }, get: function () { return m._tempexports; } }); __MODS__[modId].status = 1; __MODS__[modId].func(__MODS__[modId].req, m, m.exports); } return __MODS__[modId].m.exports; };
var __REQUIRE_WILDCARD__ = function(obj) { if(obj && obj.__esModule) { return obj; } else { var newObj = {}; if(obj != null) { for(var k in obj) { if (Object.prototype.hasOwnProperty.call(obj, k)) newObj[k] = obj[k]; } } newObj.default = obj; return newObj; } };
var __REQUIRE_DEFAULT__ = function(obj) { return obj && obj.__esModule ? obj.default : obj; };
__DEFINE__(1754927985119, function(require, module, exports) {
var u=Object.defineProperty;var C=Object.getOwnPropertyDescriptor;var O=Object.getOwnPropertyNames;var _=Object.prototype.hasOwnProperty;var T=(t,e)=>{for(var n in e)u(t,n,{get:e[n],enumerable:!0})},E=(t,e,n,r)=>{if(e&&typeof e=="object"||typeof e=="function")for(let i of O(e))!_.call(t,i)&&i!==n&&u(t,i,{get:()=>e[i],enumerable:!(r=C(e,i))||r.enumerable});return t};var j=t=>E(u({},"__esModule",{value:!0}),t);var q={};T(q,{init:()=>w});module.exports=j(q);var o,h=()=>o,g=t=>{o=t},s=class{constructor(e){this._queue=[];this._time=0;this._flushTimer=null;this.colletEvent=null;this._options=e,e.dsn?this._dsn=e.dsn:console.debug("options missing dsn"),this._transport=e.transport}init(){let{plugins:e}=this._options;console.log("client init"),e.forEach(n=>{n(this._options)})}sendEvent(){this._queue.length!==0&&(this._flushTimer!==null?(clearTimeout(this._flushTimer),this.sendQueueHandle()):this.sendQueueHandle())}sendQueueHandle(){this._time=this._options.flushTime||this._time,this._queue.length<30?this._flushTimer=setTimeout(()=>{this._transport.send(),this.sendEvent()},this._time):(this._transport.send(),this.sendEvent())}triggerSend(e){this._queue.push(e),this.sendEvent()}getQueue(){return this._queue}};function p(t,e){if(h()!==void 0)throw new Error("client has been instantiated");{let r=new t(e);return g(r),r.init(),r}}function a(t){let e=[],n=t.defaultIntegrations()||[],r=t.plugins;r&&Array.isArray(r)?e=[...n,...r]:e=[...n],console.log("totalPlugins",e[0]);let i=[];return e.length>0&&e.forEach(y=>{let x=y();i.push(x)}),i}function d(t,e){function n(){e(t)}return{send:n}}var l=class extends s{constructor(e){super(e)}};function f(t){function e(n){let r={data:n.body,method:"POST",...t.requestOptions};wx.request({url:t.url,...r})}return d(t,e)}var c={error:[],unhandledrejection:[]};function b(){return function(t={}){if(o===void 0)throw new Error("client is not instantiated");let e={onerror:!0,onunhandledrejection:!0,...t};e.onerror&&v(),e.onunhandledrejection&&R()}}function v(){wx.onError(t=>{let e={type:"error",message:t};c.error.push(e),o.triggerSend(e)})}function R(){wx.onUnhandledRejection(t=>{let e={type:"unhandledrejection",message:t};c.unhandledrejection.push(e),o.triggerSend(e)})}function m(){return[b]}function w(t){console.log("init");let e={...t,plugins:a({defaultIntegrations:t.defaultIntegrations?m:[],plugins:t.plugins||[]}),transport:t.transport||f};return p(l,e)}0&&(module.exports={init});
//# sourceMappingURL=index.js.map
}, function(modId) {var map = {}; return __REQUIRE__(map[modId], modId); })
return __REQUIRE__(1754927985119);
})()
//miniprogram-npm-outsideDeps=[]
//# sourceMappingURL=index.js.map